version: '3.7'

x-demo: &demo
  image: demo
  env_file:
    - .env
  environment:
    - FLASK_APP=run.py
    - FLASK_CONFIG=development
  networks:
    - demo
  volumes:
    - ./:/usr/local/src

services:
  database:
    image: postgres:10.6
    ports:
      - '5440:5432'
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    volumes:
      - demodb:/var/lib/postgresql/data
    networks:
      - demo
  redis:
    image: redis:alpine
    networks:
      - demo
  web:
    ports:
      - '5000:5000'
    depends_on:
      - database
    entrypoint:
      - /usr/local/src/boot.sh
    <<: *demo
  worker:
    command: 'celery worker -A demo.celery_worker.celery --loglevel=info'
    restart: always
    depends_on:
      - database
      - redis
    <<: *demo

volumes:
  demodb:

networks:
  demo:
    driver: bridge
